sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - TESTS_ZEND_CODE_ANNOTATION_DOCTRINE_SUPPORT=true

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - EXECUTE_CS_CHECK=true
    - php: 7
    - php: hhvm 
  allow_failures:
    - php: 7
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
